### ISSUE TITLE
OpenSearchStatusException class not found

### ISSUE THREAD

**Issue by dmathieu** [aiven/opensearch-connector-for-apache-kafka#28]
Hi,

I am trying to run this connector on my cluster.
I am downloading the latest version from GitHub, and putting all jar files into my plugins path. I can see all those jars in my container, including `opensearch-rest-high-level-client-1.2.3.jar`.

Yet, after starting, my connector fails with a missing class exception:

```
java.lang.NoClassDefFoundError: org/opensearch/OpenSearchStatusException
        at io.aiven.kafka.connect.opensearch.OpensearchSinkTask.start(OpensearchSinkTask.java:77)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:308)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:182)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:231)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.opensearch.OpenSearchStatusException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 10 more
```

**Comment by willyborankin** [comment]
Thank you for reporting the issue. All integration tests passed without any problems and this connector already is in production services with successful deployments. Could you please provide additional information on how did you get this exception?

**Comment by dmathieu** [comment]
Hi,

I am trying out a switch from [this fork of the confluent plugin](https://github.com/dmathieu/kafka-connect-opensearch) to your plugin. The configuration works properly with our own fork.

Here is what my Dockerfile looks like:

```
ARG KAFKA_CONNECT_VERSION
ARG AIVEN_KAFKA_CONNECT_OPENSEARCH_VERSION
ARG UBUNTU_VERSION
FROM ubuntu:${UBUNTU_VERSION} as build_jar

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
  apt-get install -yq git maven curl

ARG AIVEN_KAFKA_CONNECT_OPENSEARCH_VERSION
RUN curl --fail -L -o /tmp/aiven-kafka-connect-opensearch.tar https://github.com/aiven/opensearch-connector-for-apache-kafka/releases/download/v${AIVEN_KAFKA_CONNECT_OPENSEARCH_VERSION}/opensearch-connector-for-apache-kafka-${AIVEN_KAFKA_CONNECT_OPENSEARCH_VERSION}.tar
RUN cd /tmp && tar -xvf /tmp/aiven-kafka-connect-opensearch.tar

FROM confluentinc/cp-kafka-connect:${KAFKA_CONNECT_VERSION}

ARG AIVEN_KAFKA_CONNECT_OPENSEARCH_VERSION
RUN mkdir /usr/share/java/auth0
COPY --from=build_jar /tmp/opensearch-connector-for-apache-kafka-${AIVEN_KAFKA_CONNECT_OPENSEARCH_VERSION}/* /usr/share/java/auth0/

USER root
RUN yum install jq -y
RUN chown appuser:appuser /usr/share/java/auth0/*
USER appuser
```

Then, when starting it, I set the folllowing environment variable so the plugin is properly loaded. As the `OpensearchSinkTask` class is found, the main jar file is properly loaded.

```
CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/usr/share/java/auth0"
```

I'm happy to give you more specific information if you need.

**Comment by willyborankin** [comment]
Thank you will try to re-produce the problem.

**Comment by reta** [comment]
@dmathieu ok, so dependency is here, I can see it `opensearch-1.2.3.jar` (for `OpenSearchStatusException`), so the issue seems to be related to plugin classpath isolation. I have found this interesting thread [1] on the similar issue, could you please share the logs so we could find out what the classpath is, thank you!

[1] https://forums.couchbase.com/t/about-class-loading-isolation-and-converter-class/14591/6

**Comment by dmathieu** [comment]
The logs do not make any mention of CLASSPATH: https://gist.github.com/dmathieu/40533c7e29c358b68d068ffd7e62f160 (I will delete this gist in a couple days).

We also don't override it ourselves. So it remains the default from the base `confluentinc/cp-kafka-connect` image.

**Comment by reta** [comment]
@dmathieu I was able to reproduce the issue and it seems to be related to the Kafka Connect plugin's layout, I changed your deployment a little bit and things are kicked off for me. There are 2 changes:

- I deployed everything to `/usr/share/auth0/` (not `/usr/share/java/auth0/`):
```
RUN mkdir -p /usr/share/auth0/lib
```
- and, more importantly, I copied plugin JARs to `/usr/share/auth0/lib` folder (not `/usr/share/auth0/`):
```
COPY --from=build_jar /tmp/opensearch-connector-for-apache-kafka-${AIVEN_KAFKA_CONNECT_OPENSEARCH_VERSION}/* /usr/share/java/auth0/lib/
```

The `CONNECT_PLUGIN_PATH` changes slightly to:

```
CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/usr/share/auth0"
```

And with that, the connector starts successfully:

```
tch.size = 2000
        behavior.on.malformed.documents = fail
        behavior.on.null.values = ignore
        compact.map.entries = true
        connection.password = null
        connection.timeout.ms = 1000
        connection.url = [opensearch:9200]
        connection.username = null
        drop.invalid.message = false
        flush.timeout.ms = 10000
        key.ignore = false
        linger.ms = 1
        max.buffered.records = 20000
        max.in.flight.requests = 5
        max.retries = 5
        read.timeout.ms = 3000
        retry.backoff.ms = 100
        schema.ignore = false
        topic.index.map = []
        topic.key.ignore = []
        topic.schema.ignore = []
 (io.aiven.kafka.connect.opensearch.OpensearchSinkConnectorConfig)
[2022-02-21 17:02:42,953] INFO WorkerSinkTask{id=quickstart-0} Sink task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2022-02-21 17:02:42,956] INFO [Consumer clientId=connector-consumer-quickstart-0, groupId=connect-quickstart] Cluster ID: 2NtFdOQGQsqZb4Hd69VIHA (org.apache.kafka.clients.Metadata)
[2022-02-21 17:02:42,956] INFO [Consumer clientId=connector-consumer-quickstart-0, groupId=connect-quickstart] Discovered group coordinator coordinator:9092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2022-02-21 17:02:42,957] INFO [Consumer clientId=connector-consumer-quickstart-0, groupId=connect-quickstart] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2022-02-21 17:02:42,959] INFO [Consumer clientId=connector-consumer-quickstart-0, groupId=connect-quickstart] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2022-02-21 17:02:42,960] INFO [Consumer clientId=connector-consumer-quickstart-0, groupId=connect-quickstart] Successfully joined group with generation Generation{generationId=3, memberId='connector-consumer-quickstart-0-bafa0241-50b2-40a6-b0b5-3b6960a71a79', protocol='range'} (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2022-02-21 17:02:42,960] INFO [Consumer clientId=connector-consumer-quickstart-0, groupId=connect-quickstart] Finished assignment for group at generation 3: {connector-consumer-quickstart-0-bafa0241-50b2-40a6-b0b5-3b6960a71a79=Assignment(partitions=[quickstart-0])} (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2022-02-21 17:02:42,962] INFO [Consumer clientId=connector-consumer-quickstart-0, groupId=connect-quickstart] Successfully synced group in generation Generation{generationId=3, memberId='connector-consumer-quickstart-0-bafa0241-50b2-40a6-b0b5-3b6960a71a79', protocol='range'} (org.apache.kafka.clients.consumer.internals.AbstractCoordinator)
[2022-02-21 17:02:42,962] INFO [Consumer clientId=connector-consumer-quickstart-0, groupId=connect-quickstart] Notifying assignor about the new Assignment(partitions=[quickstart-0]) (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2022-02-21 17:02:42,962] INFO [Consumer clientId=connector-consumer-quickstart-0, groupId=connect-quickstart] Adding newly assigned partitions: quickstart-0 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2022-02-21 17:02:42,963] INFO [Consumer clientId=connector-consumer-quickstart-0, groupId=connect-quickstart] Found no committed offset for partition quickstart-0 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator)
[2022-02-21 17:02:42,965] INFO [Consumer clientId=connector-consumer-quickstart-0, groupId=connect-quickstart] Resetting offset for partition quickstart-0 to position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[leader:9092 (id: 0 rack: null)], epoch=0}}. (org.apache.kafka.clients.consumer.internals.SubscriptionState)

```

Could you please try out this layout instead? 
Thank you.

**Comment by dmathieu** [comment]
Thank you @reta. I suppose my library being an uber jar, it doesn't need to be in the lib folder. Moving your into `/usr/share/java/auth0/lib` allowed me to use your connector.
