### ISSUE TITLE
java.lang.NoClassDefFoundError: org/opensearch/client/RestClientBuilder

### ISSUE THREAD

**Issue by forrestrice** [aiven/opensearch-connector-for-apache-kafka#76]
## Problem Overview
Hello, I have been trying to use this project to ingest data from kafka into an OpenSearch cluster. I got this to work with [kafka-connect-opensearch](https://github.com/dmathieu/kafka-connect-opensearch) but I see that project has been archived in favor of this one.

I started by building the jar from this project and including it with a simple docker file (some fields redacted).
```
FROM confluentinc/cp-kafka-connect-base

ADD lib/opensearch-connector-for-apache-kafka-1.1.0-SNAPSHOT.jar /usr/share/java/

ENV CONNECT_GROUP_ID=ds-events-index
ENV CONNECT_CONFIG_STORAGE_TOPIC=$TOPIC1
ENV CONNECT_OFFSET_STORAGE_TOPIC=$TOPIC2
ENV CONNECT_STATUS_STORAGE_TOPIC=$TOPIC3
ENV CONNECT_KEY_CONVERTER="org.apache.kafka.connect.storage.StringConverter"
ENV CONNECT_VALUE_CONVERTER="org.apache.kafka.connect.storage.StringConverter"
ENV CONNECT_REST_ADVERTISED_HOST_NAME="localhost"
```
I see in the logs that the plugin classes are added
```
[2022-06-06 18:04:14,844] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/java/opensearch-connector-for-apache-kafka-1.1.0-SNAPSHOT.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2022-06-06 18:04:14,845] INFO Added plugin 'io.aiven.kafka.connect.opensearch.OpensearchSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
```

However when I try to submit a connector configuration like this
```
{
  "name": "ds-events-elasticsink-datastream",
  "config": {
    "connector.class": "io.aiven.kafka.connect.opensearch.OpensearchSinkConnector",
    "topics": $TOPIC,
    "connection.url": $URL,
    "connection.username": $USSER,
    "connection.password": $PASSWORD,
    "type.name": "kafka-connect",
    "key.ignore": true,
    "schema.ignore": true,
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false",
    "key.converter.schemas.enable": "false",
    "errors.tolerance": "none",
    "data.stream.type": "logs",
    "data.stream.dataset": "psearch",
    "data.stream.timestamp.field": "timestamp"
  }
}
```
I see this error in the logs:
```
[2022-06-06 18:05:24,150] INFO Starting OpensearchSinkTask. (io.aiven.kafka.connect.opensearch.OpensearchSinkTask)
[2022-06-06 18:05:24,153] INFO OpensearchSinkConnectorConfig values: 
	batch.size = 2000
	behavior.on.malformed.documents = fail
	behavior.on.null.values = ignore
	compact.map.entries = true
	connection.password = [hidden]
	connection.timeout.ms = 1000
	connection.url = [REDACTED]
	connection.username = REDACTED
	drop.invalid.message = false
	flush.timeout.ms = 10000
	key.ignore = true
	linger.ms = 1
	max.buffered.records = 20000
	max.in.flight.requests = 5
	max.retries = 5
	read.timeout.ms = 3000
	retry.backoff.ms = 100
	schema.ignore = true
	topic.index.map = []
	topic.key.ignore = []
	topic.schema.ignore = []
 (io.aiven.kafka.connect.opensearch.OpensearchSinkConnectorConfig)
[2022-06-06 18:05:24,167] ERROR WorkerSinkTask{id=ds-events-elasticsink-datastream-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
java.lang.NoClassDefFoundError: org/opensearch/client/RestClientBuilder$HttpClientConfigCallback
	at io.aiven.kafka.connect.opensearch.OpensearchSinkTask.start(OpensearchSinkTask.java:77)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:312)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.opensearch.client.RestClientBuilder$HttpClientConfigCallback
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:103)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 9 more
[2022-06-06 18:05:24,174] INFO Stopping OpensearchSinkTask. (io.aiven.kafka.connect.opensearch.OpensearchSinkTask)
```

This appears to be a classpath issue or an issue with how I built the jar. I have tried two solutions so far:
## Attempted Solution 1: Include dependency jars and add them to classpath
I added this to the dockerfile
```
ADD lib/opensearch-rest-high-level-client-1.3.1.jar /usr/share/java/opensearch_deps/
ADD lib/gson-2.9.0.jar /usr/share/java/opensearch_deps/
ADD lib/slf4j-api-1.7.36.jar /usr/share/java/opensearch_deps/
ENV CLASSPATH="$CLASSPATH:/usr/share/java/opensearch_deps/slf4j-api-1.7.36.jar:/usr/share/java/opensearch_deps/gson-2.9.0.jar:/usr/share/java/opensearch_deps/opensearch-rest-high-level-client-1.3.1.jar"
```
I see the classpath has been updated when kafka-connect starts up, but the same error persists.
```
===> Launching kafka-connect ... 
[2022-06-06 18:20:16,215] INFO WorkerInfo values: 
	jvm.args = -Xms256M, -Xmx2G, -XX:+UseG1GC, -XX:MaxGCPauseMillis=20, -XX:InitiatingHeapOccupancyPercent=35, -XX:+ExplicitGCInvokesConcurrent, -XX:MaxInlineLevel=15, -Djava.awt.headless=true, -Dcom.sun.management.jmxremote=true, -Dcom.sun.management.jmxremote.authenticate=false, -Dcom.sun.management.jmxremote.ssl=false, -Dkafka.logs.dir=/var/log/kafka, -Dlog4j.configuration=file:/etc/kafka/connect-log4j.properties
	jvm.spec = Azul Systems, Inc., OpenJDK 64-Bit Server VM, 11.0.14.1, 11.0.14.1+1-LTS
	jvm.classpath = /usr/share/java/opensearch_deps/slf4j-api-1.7.36.jar:/usr/share/java/opensearch_deps/gson-2.9.0.jar:/usr/share/java/opensearch_deps/opensearch-rest-high-level-client-1.3.1.jar:/usr/share/java/kafka/jetty-io-9.4.44.v20210927.jar...
```

## Attempted solution 2: build an uber jar.
I know very little about gradle, but i followed the instructions for [building an uber jar](https://docs.gradle.org/current/userguide/working_with_files.html#sec:creating_uber_jar_example) and added this configuration to build.gradle
```
tasks.register('uberJar', Jar) {
    archiveClassifier = 'uber'
    duplicatesStrategy = DuplicatesStrategy.WARN

    from sourceSets.main.output

    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.findAll { it.name.endsWith('jar') }.collect { zipTree(it) }
    }
}
```
I then added that uber jar to my docker image (instead of the jar from above)
```
ADD lib/opensearch-connector-for-apache-kafka-1.1.0-SNAPSHOT-uber.jar /usr/share/java/
```
However, now when kafka-connect starts up the aiven plugin is not loaded correctly.
```
[2022-06-06 18:36:30,167] INFO Loading plugin from: /usr/share/java/opensearch-connector-for-apache-kafka-1.1.0-SNAPSHOT-uber.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2022-06-06 18:37:24,025] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/java/opensearch-connector-for-apache-kafka-1.1.0-SNAPSHOT-uber.jar} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
```
This line from solution 1 is missing:
```
[2022-06-06 18:04:14,845] INFO Added plugin 'io.aiven.kafka.connect.opensearch.OpensearchSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
```
And this error happens:
```
[2022-06-06 18:38:37,329] ERROR Failed to start task ds-events-elasticsink-datastream-0 (org.apache.kafka.connect.runtime.Worker)
org.apache.kafka.common.config.ConfigException: Invalid value io.aiven.kafka.connect.opensearch.OpensearchSinkTask for configuration task.class: Class io.aiven.kafka.connect.opensearch.OpensearchSinkTask could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:744)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:113)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:146)
	at org.apache.kafka.connect.runtime.TaskConfig.<init>(TaskConfig.java:51)
	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:511)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1421)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$getTaskStartingCallable$22(DistributedHerder.java:1434)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by willyborankin** [comment]
Hi @forrestrice, thank you for the reporting the issue. It looks similar to https://github.com/aiven/opensearch-connector-for-apache-kafka/issues/28. Could you please take a look?

**Comment by forrestrice** [comment]
@willyborankin yes this worked, thank you!
